---
output: github_document
editor_options: 
  markdown: 
    wrap: 72
---

<!-- README.md is generated from README.Rmd. Please edit the README.Rmd file -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lab report #1

Follow the instructions posted at
<https://ds202-at-isu.github.io/labs.html> for the lab assignment. The
work is meant to be finished during the lab time, but you have time
until Monday evening to polish things.

Include your answers in this document (Rmd file). Make sure that it
knits properly (into the md file). Upload both the Rmd and the md file
to your repository.

All submissions to the github repo will be automatically uploaded for
grading once the due date is passed. Submit a link to your repository on
Canvas (only one submission per team) to signal to the instructors that
you are done with your submission.

Hi

All submissions to the github repo will be automatically uploaded for
grading once the due date is passed. Submit a link to your repository on
Canvas (only one submission per team) to signal to the instructors that
you are done with your submission.

R-studio is very difficult to use. We should use something else instead.

Problems we had with:

-   12.3 Clone the test GitHub repository to your computer via RStudio

    -   We had no problems cloning the repository into RStudio.

-   12.4 Make local changes, save, commit

    -   We had no problems making changes until we needed to commit and
        push the changes at the end. We found out that we needed to
        connect our github account to git in order to commit changes.

-   12.5 Push your local changes online to GitHub

    -   When pushing there were some conflicts. We determined that the
        conflicts occured because we dodnt hit commit before trying to
        push the document.
